let equipmentstb = [
    {
        id: 1,
        thumbnail: '../../assets/image/Crane 1.jpg',
        equipmentName: 'Hammer',
        vendorName: 'Vinhomes',
        importDate: '22/12/2017',
        price: '100 000',
        description: 'A hammer',
        category: 'tools',
        department: 'department a',
    },
    {
        id: 2,
        thumbnail: '../../assets/image/Crane 1.jpg',
        equipmentName: 'Hammer',
        vendorName: 'Vinhomes',
        importDate: '25/12/2017',
        price: '1300 000',
        description: 'A saw',
        category: 'tools',
        department: 'department a',
        
    },
    {
        id: 3,
        thumbnail: '../../assets/image/Crane 1.jpg',
        equipmentName: 'Hammer',
        vendorName: 'Vinhouse',
        importDate: '25/02/2017',
        price: '300 000',
        description: 'An axe',
        category: 'tools',
        department: 'department a',
    },
    {
        id: 4,
        thumbnail: '../../assets/image/Crane 1.jpg',
        equipmentName: 'Hammer',
        vendorName: 'Vinhouse',
        importDate: '25/02/2017',
        price: '300 000',
        description: 'An axe',
        category: 'tools',
        department: 'department a',
    },
    {
        id: 5,
        thumbnail: '../../assets/image/Crane 1.jpg',
        equipmentName: 'Hammer',
        vendorName: 'Vinhouse',
        importDate: '25/02/2017',
        price: '300 000',
        description: 'An axe',
        category: 'tools',
        department: 'department a',
    },
    {
        id: 6,
        thumbnail: '../../assets/image/Crane 1.jpg',
        equipmentName: 'Hammer',
        vendorName: 'Vinhouse',
        importDate: '25/02/2017',
        price: '300 000',
        description: 'An axe',
        category: 'tools',
        department: 'department a',
    },
]
export default equipmentstb;