let location = [
    {
        id: 1,
        name: 'chung cu hung yen',
        address: '31 to ky phuong tan thoi hiep quan 12',
        siteManager: 'Lai Duc Hung',
        equipmentQuantity: 18,
    },
    {
        id: 2,
        name: 'new world plaza',
        address: '23 tan thanh phuong 18 quan 1',
        siteManager: 'Vo Nguyen Giap',
        equipmentQuantity: 29,
    },
    {
        id: 3,
        name: 'biet thu cover',
        address: '312 thanh thien phuong 4 quan 8',
        siteManager: 'Ly Chinh Thang',
        equipmentQuantity: 182,
    },
    {
        id: 4,
        name: 'chung cu quoc thanh',
        address: '318 le van can phuong 9 quan phu nhuan',
        siteManager: 'Vo Thanh Tan',
        equipmentQuantity: 75,
    },
    {
        id: 5,
        name: 'chung cu phi long',
        address: '77 ly nam de phuong tan thanh quan 11',
        siteManager: 'Dam Vinh Hung',
        equipmentQuantity: 195, 
    },
    {
        id: 6,
        name: 'chung cu thien thanh',
        address: '771 quang trung phuong nguyen thanh quan tan phu',
        siteManager: 'Nguyen Hung',
        equipmentQuantity: 5, 
    },
    {
        id: 7,
        name: 'Home Pub',
        address: '221 tan tao phuong 15 quan binh tan',
        siteManager: 'Trinh Thang Binh',
        equipmentQuantity: 29, 
    },
    {
        id: 8,
        name: 'sai gon square',
        address: '65 tran hung dao 10 quan 1',
        siteManager: 'Trinh Cong Son',
        equipmentQuantity: 292, 
    },
    {
        id: 9,
        name: 'Thanh Thanh cinema',
        address: '65 tao lao phuong 1 quan binh tan',
        siteManager: 'Tap Can Binh',
        equipmentQuantity: 30, 
    },
    {
        id: 10,
        name: 'SuperMarket',
        address: '23 tan van vo phuong 15 quan 3',
        siteManager: 'Luu Ba On',
        equipmentQuantity: 292, 
    },
    {
        id: 11,
        name: 'Thanh Thien Temple',
        address: '2212 Kim Chung phuong 2 quan tan phu',
        siteManager: 'Nguyen Phi Hung',
        equipmentQuantity: 293, 
    },
    {
        id: 12,
        name: 'Can Tho Center',
        address: '23 Alexander phuong 7 quan tan binh',
        siteManager: 'Hoai Linh',
        equipmentQuantity: 39, 
    },
]
export default location;