let orders = [
    {
        id: 1,
        name: 'Hammer - Vinhomes',
        priority: 'Urgent',
        orderNumber: '001',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
    },
    {
        id: 2,
        name: 'Saw - Vinhomes',
        priority: 'Urgent',
        orderNumber: '001',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
    },
    {
        id: 3,
        name: 'Axe - Vinhomes',
        priority: 'Urgent',
        orderNumber: '001',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
    },
    {
        id: 4,
        name: 'Cement - Vinhomes',
        priority: 'High',
        orderNumber: '001',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
    },
    {
        id: 5,
        name: 'Axe - Vinhomes',
        priority: 'Urgent',
        orderNumber: '001',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
    },
    {
        id: 6,
        name: 'Cement - Vinhomes',
        priority: 'Urgent',
        orderNumber: '001',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
    },
]

export default orders;