let orders = [
    {
        id: 1,
        name: 'Hammer - Vinhomes',
        priority: 'Urgent',
        tagColor: '#ab47bc',
        orderNumber: '001',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
        requestDate: '2017-12-11',
    },
    {
        id: 2,
        name: 'Saw - Vinhomes',
        priority: 'High',
        tagColor: '#ef5350',
        orderNumber: '001',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
        requestDate: '2017-12-10',
    },
    {
        id: 3,
        name: 'Pickaxe - Vinhomes',
        priority: 'Medium',
        tagColor: '#fbc02d',
        orderNumber: '001',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
        requestDate: '2017-12-10',
    },
    {
        id: 4,
        name: 'Cement - Vinhomes',
        priority: 'Low',
        tagColor: '#00c853',
        orderNumber: '001',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
        requestDate: '2017-12-10',
    },
    {
        id: 5,
        name: 'Axe - Vinhomes',
        priority: 'Urgent',
        tagColor: '#ab47bc',
        orderNumber: '001',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
        requestDate: '2017-12-10',
    },
    {
        id: 6,
        name: 'Cement - Vinhomes',        
        priority: 'Low',
        tagColor: '#00c853',
        createdBy: 'Minh Tien',
        status: 'Open',
        location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
        requestDate: '2017-12-13',
    },
    // {
    //     id: 7,
    //     name: 'Cement - Vinhomes',
    //     priority: 'Low',
    //     tagColor: '#00c853',
    //     orderNumber: '001',
    //     createdBy: 'Minh Tien',
    //     status: 'Open',
    //     location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
    //     requestDate: '2017-12-10',
    // },
    // {
    //     id: 8,
    //     name: 'Axe - Vinhomes',
    //     priority: 'Urgent',
    //     tagColor: '#ab47bc',
    //     orderNumber: '001',
    //     createdBy: 'Minh Tien',
    //     status: 'Open',
    //     location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
    //     requestDate: '2017-12-10',
    // },
    // {
    //     id: 9,
    //     name: 'Cement - Vinhomes',        
    //     priority: 'Low',
    //     tagColor: '#00c853',
    //     createdBy: 'Minh Tien',
    //     status: 'Open',
    //     location: '27 Truong Chinh, phuong Tan Thoi Nhat, quan 12, tp. Ho Chi Minh',
    //     requestDate: '2017-12-13',
    // },
]

export default orders;